### ISSUE TITLE
hacks for sanity tests goe hephy

### ISSUE THREAD

**Issue by BenjaminSchwenker** [SiLab-Bonn/tj-monopix2-daq#13]

**Comment by BenjaminSchwenker** [comment]
@cbespin : it seems we have insufficient rights to create even a new branch on this repo. 

For our first sanity testing jointly with Hephy and Goe ( @maxbab1  @MarikeSchwickardi ), we would like to have the option to share among us some code modifications. until we have learned how it is done in your code. 

Oder sollen wir das forken? @themperek how do you want to organize this? with forks or giving us some rights to create branches to address issues?

**Comment by cbespin** [comment]
To create branches one needs write access to a repository which I have to manage on a user by user basis. I added it now for the three of you.

Nevertheless we encourage to work in a forked repository, test, modify and share with each other as much as you want and make a pull-request or feature branch if you developed something that is useful for others.
